# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Select target'
        type: choise
        required: true
        options:
          - client1-prod
          - client2-prod
          - client1-staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }}
    steps:
    - uses: actions/checkout@v4
    - name: Test
      shell: bash
      run: "echo $HOSTLIST"
